import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/bg1.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
       <Layout className='pt-0'>
        <div className='flex items-center justify-between w-full '>
          <div className='w-1/2 '>
            <Image src={profilePic} alt="srijit" className='w-full h-auto'>

            </Image>
          </div>
          <div>
            <h1>
            Transforming Data into Intelligence: Where Algorithms Meet Ingenuity!
            </h1>
            <p>
            Transforming ideas into intelligent solutions. Explore my latest projects showcasing expertise in machine learning, Python, TensorFlow, and scikit-learn. From predictive analytics to deep learning, let's redefine what's possible in the world of intelligent systems
            </p>
          </div>
        </div>

       </Layout>
      </main>
      </>
        )
}
